server:
  port: 10012
spring:
  application:
    name: item-service
spring.jpa:
    show-sql: true
    database: MYSQL
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddemo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:10001/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true